### ISSUE TITLE
Set msg.payload to boolean instead of present/not-present

### ISSUE THREAD

**Issue by johnwalicki** [sbernhard/node-red-contrib-bt-presence#2]
I like the node-red-contrib-bt-presence idea.  I had been using a flow wrapped around node-red-contrib-noble and the npm noble package to detect the presence of a Bluetooth device.   This node is much easier and doesn't drag in the complexity of the noble install.

Instead of setting msg.payload to strings "present" / "not-present", it would be easier to program for a msg.payload boolean flag.

**Comment by pastukhov** [comment]
or maybe msg.present with bool type

**Comment by johnwalicki** [comment]
@sbernhard - If I write a quick node-red-contrib-bt-presense patch to change "present" / "not-present" to boolean true / false, would you accept it upstream?

**Comment by sbernhard** [comment]
Sure. Every PR is welcomed.


---- John Walicki schrieb ----


@sbernhard<https://github.com/sbernhard> - If I write a quick node-red-contrib-bt-presense patch to change "present" / "not-present" to boolean true / false, would you accept it upstream?

**Comment by sbernhard** [comment]
@johnwalicki and @pastukhov Fixed in version 1.1.3 (available on npm)

msg.payload = true is set on presence. Otherwise false.
