### ISSUE TITLE
no interval

### ISSUE THREAD

**Issue by jcheger** [sbernhard/node-red-contrib-bt-presence#5]
I've got the version 1.1.1 installed on a fresh new install of node-red. After deploying, I get a message telling my phone is detected - perfect. But interval is not working, and bt-presence does not do anything afterward.

Logs say:
[bt-presence:JC-GS7] Starting Bluetooth scan for 1 devices every 20 seconds!

and nothing more

**Comment by sbernhard** [comment]
Sorry for the (very very) long answer. It will send a message only on a change. Turn off your mobile phone bluetooth and bt-presence will tell you that the device is not reachable anymore. The 'interval' is the time in seconds between two checks. 

Please tell me if your issue is fixed.
