### ISSUE TITLE
Report every ping

### ISSUE THREAD

**Issue by borpin** [sbernhard/node-red-contrib-bt-presence#6]
Rather than create a separate node for each device to be pinged, I have created a branch (https://github.com/borpin/node-red-contrib-bt-presence/tree/bpo) that will use a new listener I have created for `bt-presence` (https://github.com/cmvee/bt-presence/pull/9)  to return every ping result.

This has 2 additional configuration items, a `topic` item and a checkbox to set whether to output all pings or just the original output.

The specified topic will be prepended onto the mac address as the output topic.  This can then be easily used in the likes of Home Assistant.

By default this is not a breaking change.

I have not pushed it as it requires the modified `bt-presence` node.  If you wish it could go into a new Branch.

**Comment by sbernhard** [comment]
Very cool idea! Would love to merge it. Hopefully it gets merged soon into bt-presence. Than we can merge this feature back in node-red-contrib-bt-presence. 

Thank you!
